# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import array as arr


affairs = []

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 550)
        MainWindow.setMinimumSize(QtCore.QSize(780, 550))
        MainWindow.setMaximumSize(QtCore.QSize(780, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.objFeeld = QtWidgets.QFrame(self.centralwidget)
        self.objFeeld.setEnabled(True)
        self.objFeeld.setGeometry(QtCore.QRect(-1, 0, 801, 552))
        self.objFeeld.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"background-image: url(/Users/nikolaismirnov/Documents/GitHub/ToDo/resources/bg_3.png);\n")
        self.objFeeld.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.objFeeld.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.objFeeld.setObjectName("objFeeld")
        self.addButton = QtWidgets.QPushButton(self.objFeeld)
        self.addButton.setEnabled(True)
        self.addButton.setGeometry(QtCore.QRect(700, 490, 50, 50))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.addButton.setStyleSheet("QPushButton {\n"
"    background-image: url(/Users/nikolaismirnov/Documents/GitHub/ToDo/resources/add_button.png);\n"
"    border: none;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    overflow: hidden;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-image: url(/Users/nikolaismirnov/Documents/GitHub/ToDo/resources/add_button_hover.png);\n"
"    border: none;\n"
"    outline: none;\n"
"    border-radius: 5px;\n"
"    overflow: hidden;\n"
"}")
        self.addButton.setText("")
        self.addButton.setObjectName("addButton")
        self.scrollArea = QtWidgets.QScrollArea(self.objFeeld)
        self.scrollArea.setGeometry(QtCore.QRect(20, 10, 761, 470))
        self.scrollArea.setStyleSheet("border: none;\n"
"background: rgba(255, 255, 255, 0);")
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 761, 650))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.addButton.raise_()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def add_item(self):
        self.Item_n = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.Item_n.setEnabled(True)
        self.Item_n.setMinimumSize(QtCore.QSize(0, 110))
        self.Item_n.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Item_n.setStyleSheet("background: rgb(1, 1, 1);")
        self.Item_n.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Item_n.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Item_n.setObjectName("Item_n")
        self.label_n_1 = QtWidgets.QLabel(self.Item_n)
        self.label_n_1.setGeometry(QtCore.QRect(10, 40, 721, 61))
        self.label_n_1.setMinimumSize(QtCore.QSize(0, 61))
        self.label_n_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.label_n_1.setStyleSheet("background: rgba(225, 225, 225, 150);\n"
                                     "border-bottom-left-radius: 10px;\n"
                                     "border-bottom-right-radius: 10px;\n"
                                     "font-size: 20px;\n"
                                     "padding: 5px 15px 5px 15px;")
        self.label_n_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_n_1.setScaledContents(False)
        self.label_n_1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_n_1.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_n_1.setObjectName("label_43")
        self.label_n_2 = QtWidgets.QLabel(self.Item_n)
        self.label_n_2.setGeometry(QtCore.QRect(10, 10, 51, 31))
        self.label_n_2.setStyleSheet("font-size: 22px;\n"
                                     "background-color: rgb(125, 232, 109);\n"
                                     "color: white;\n"
                                     "border-top-left-radius: 10px;")
        self.label_n_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_n_2.setObjectName("label_44")
        self.label_n_3 = QtWidgets.QLabel(self.Item_n)
        self.label_n_3.setGeometry(QtCore.QRect(60, 10, 671, 31))
        self.label_n_3.setStyleSheet("background-color: rgb(228, 247, 246);\n"
                                     "border-top-right-radius: 10px;\n"
                                     "font-size: 18px;\n"
                                     "padding-left: 15px;")
        self.label_n_3.setObjectName("label_45")
        self.verticalLayout.addWidget(self.Item_n)
        return self.Item_n

    def add_affairs(self, MainWindow):
        affairs.append(self.add_item())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo"))
